services:
  backend:
    build: ./backend
    #dockerfile: Dockerfile-xyzname -- If using a different name
    container_name: travelmemory_backend
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      MONGO_URI: "mongodb://admin:xxxxxx@mongodb_tbtm:27017/travelmemory?authsource=admin"
    networks:
      - b16atm
    depends_on:
      - database

  database:
    image: mongo:latest
    container_name: mongodb_tbtm
    # ports:
    #   - "27019:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - b16atm
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: xxxxxxx
      MONGO_INITDB_DATABASE: travelmemory

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    environment:
      REACT_APP_BASE_URL: "http://localhost:3001"
    networks:
      - b16atm
      
volumes:
  mongodb-data:

networks:
  b16atm: