services:
  backend:
    build: ./backend
    #dockerfile: Dockerfile-xyzname -- If using a different name
    container_name: tm_b16a_backend
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      MONGO_URI: "mongodb://admin:password123@tm_b16a_database:27017/travelmemory?authsource=admin"
    networks:
      - tmb16a_network
    depends_on:
      - database

  database:
    image: mongo
    container_name: tm_b16a_database
    # ports:
    #   - "27019:27017"
    volumes:
      - mongo_data_tm:/data/db
    networks:
      - tmb16a_network
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: travelmemory

volumes:
  mongo_data_tm:

networks:
  tmb16a_network: