[webserver]
web_server ansible_host=98.92.149.214

[dbserver]
db_server ansible_host=10.0.2.190

[dbserver:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q ubuntu@{{ hostvars[\'web_server\'][\'ansible_host\'] }} -i ~/.ssh/travelmemory-key.pem"'

[all:vars]
ansible_user=ubuntu